name: GCP Deploy via WIF

on:
  push:
    paths:
      - '**'
    branches:
      - main           # Trigger only on main branch (adjust if needed)

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/57920515119/locations/global/workloadIdentityPools/github-actions-pool/providers/github'
          service_account: 'github-actions-sa@sylvan-hydra-464904-d9.iam.gserviceaccount.com'

      # Example: Deploy or run GCP command
      - name: Run gcloud command
        run: |
          gcloud info
          gcloud config list
